apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  namespace: default
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: voklur/mysql:V1
        ports: 
        - name: vprodb-port
          containerPort: 3000
        env: 
         - name: MYSQL_ROOT_PASSWORD
           value: root
        image: voklur/mysql:V123
        ports: 
        - name: vprodb-port
          containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
              name: app-secret
              key: pass
         - name: MYSQL_DEFAULT_USER
           value: root
         - name: MYSQL_DEFAULT_DATABASE
           value: realworld
         - name: MYSQL_HOST
           valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
           - name: mysql-storage
             mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-claim
